### PR TITLE
Support scala3

### PR DESCRIPTION
**Pull request by jtjeferreira**
depends on https://github.com/nafg/slick-migration-api/pull/294

### CODE REVIEW

**Comment by jtjeferreira** [comment]
@nafg a bit late but this is ready for review :)

**Comment by jtjeferreira** [comment]
I will have a look into the failures in the next days...

**Comment by nafg** [comment]
Thanks! Sorry for the delay

**Comment by jtjeferreira** [comment]
Hi @nafg, can you make a release that includes this PR?

**Comment by nafg** [comment]
0.11.0 is released

**Comment by jtjeferreira** [comment]
> 0.11.0 is released

Thanks @nafg

**Pull request merged**
